/*
 * Underscore Backup Service Public API
 * Public and externally accessible API for the Underscore Backup Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@underscorebackup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.underscoreresearch.backup.service.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.underscoreresearch.backup.service.api.model.ShareResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ListSharesResponse
 */
@JsonPropertyOrder({
  ListSharesResponse.JSON_PROPERTY_SHARES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-03-08T21:58:23.489056400-08:00[America/Los_Angeles]")
public class ListSharesResponse {
  public static final String JSON_PROPERTY_SHARES = "shares";
  private List<ShareResponse> shares = new ArrayList<>();

  public ListSharesResponse() { 
  }

  public ListSharesResponse shares(List<ShareResponse> shares) {
    this.shares = shares;
    return this;
  }

  public ListSharesResponse addSharesItem(ShareResponse sharesItem) {
    this.shares.add(sharesItem);
    return this;
  }

   /**
   * List of shares of response.
   * @return shares
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "List of shares of response.")
  @JsonProperty(JSON_PROPERTY_SHARES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ShareResponse> getShares() {
    return shares;
  }


  @JsonProperty(JSON_PROPERTY_SHARES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShares(List<ShareResponse> shares) {
    this.shares = shares;
  }


  /**
   * Return true if this ListSharesResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListSharesResponse listSharesResponse = (ListSharesResponse) o;
    return Objects.equals(this.shares, listSharesResponse.shares);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shares);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListSharesResponse {\n");
    sb.append("    shares: ").append(toIndentedString(shares)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

