/*
 * Underscore Backup Service Public API
 * Public and externally accessible API for the Underscore Backup Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@underscorebackup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.underscoreresearch.backup.service.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.underscoreresearch.backup.service.api.model.ReleaseFileItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ReleaseResponse
 */
@JsonPropertyOrder({
  ReleaseResponse.JSON_PROPERTY_RELEASE_DATE,
  ReleaseResponse.JSON_PROPERTY_NAME,
  ReleaseResponse.JSON_PROPERTY_VERSION,
  ReleaseResponse.JSON_PROPERTY_BODY,
  ReleaseResponse.JSON_PROPERTY_CHANGE_LOG,
  ReleaseResponse.JSON_PROPERTY_FILES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-03-08T21:58:23.489056400-08:00[America/Los_Angeles]")
public class ReleaseResponse {
  public static final String JSON_PROPERTY_RELEASE_DATE = "releaseDate";
  private BigDecimal releaseDate;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public static final String JSON_PROPERTY_BODY = "body";
  private String body;

  public static final String JSON_PROPERTY_CHANGE_LOG = "changeLog";
  private String changeLog;

  public static final String JSON_PROPERTY_FILES = "files";
  private List<ReleaseFileItem> files = new ArrayList<>();

  public ReleaseResponse() { 
  }

  public ReleaseResponse releaseDate(BigDecimal releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * When was this released..
   * @return releaseDate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "When was this released..")
  @JsonProperty(JSON_PROPERTY_RELEASE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getReleaseDate() {
    return releaseDate;
  }


  @JsonProperty(JSON_PROPERTY_RELEASE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReleaseDate(BigDecimal releaseDate) {
    this.releaseDate = releaseDate;
  }


  public ReleaseResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Title of release.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Title of release.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public ReleaseResponse version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Version of release.
   * @return version
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Version of release.")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(String version) {
    this.version = version;
  }


  public ReleaseResponse body(String body) {
    this.body = body;
    return this;
  }

   /**
   * Description of release.
   * @return body
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Description of release.")
  @JsonProperty(JSON_PROPERTY_BODY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBody() {
    return body;
  }


  @JsonProperty(JSON_PROPERTY_BODY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBody(String body) {
    this.body = body;
  }


  public ReleaseResponse changeLog(String changeLog) {
    this.changeLog = changeLog;
    return this;
  }

   /**
   * Link to change log.
   * @return changeLog
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Link to change log.")
  @JsonProperty(JSON_PROPERTY_CHANGE_LOG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChangeLog() {
    return changeLog;
  }


  @JsonProperty(JSON_PROPERTY_CHANGE_LOG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChangeLog(String changeLog) {
    this.changeLog = changeLog;
  }


  public ReleaseResponse files(List<ReleaseFileItem> files) {
    this.files = files;
    return this;
  }

  public ReleaseResponse addFilesItem(ReleaseFileItem filesItem) {
    this.files.add(filesItem);
    return this;
  }

   /**
   * Files for release.
   * @return files
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Files for release.")
  @JsonProperty(JSON_PROPERTY_FILES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ReleaseFileItem> getFiles() {
    return files;
  }


  @JsonProperty(JSON_PROPERTY_FILES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFiles(List<ReleaseFileItem> files) {
    this.files = files;
  }


  /**
   * Return true if this ReleaseResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReleaseResponse releaseResponse = (ReleaseResponse) o;
    return Objects.equals(this.releaseDate, releaseResponse.releaseDate) &&
        Objects.equals(this.name, releaseResponse.name) &&
        Objects.equals(this.version, releaseResponse.version) &&
        Objects.equals(this.body, releaseResponse.body) &&
        Objects.equals(this.changeLog, releaseResponse.changeLog) &&
        Objects.equals(this.files, releaseResponse.files);
  }

  @Override
  public int hashCode() {
    return Objects.hash(releaseDate, name, version, body, changeLog, files);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReleaseResponse {\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    changeLog: ").append(toIndentedString(changeLog)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

