/*
 * Underscore Backup Service Public API
 * Public and externally accessible API for the Underscore Backup Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@underscorebackup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.underscoreresearch.backup.service.api.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.underscoreresearch.backup.service.api.model.SourceUsage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SourceResponse
 */
@JsonPropertyOrder({
  SourceResponse.JSON_PROPERTY_SOURCE_ID,
  SourceResponse.JSON_PROPERTY_NAME,
  SourceResponse.JSON_PROPERTY_CREATED,
  SourceResponse.JSON_PROPERTY_IDENTITY,
  SourceResponse.JSON_PROPERTY_DESTINATION,
  SourceResponse.JSON_PROPERTY_ENCRYPTION_MODE,
  SourceResponse.JSON_PROPERTY_SECRET_REGION,
  SourceResponse.JSON_PROPERTY_LAST_USAGE,
  SourceResponse.JSON_PROPERTY_DAILY_USAGE,
  SourceResponse.JSON_PROPERTY_PERIOD_USAGE,
  SourceResponse.JSON_PROPERTY_APPLICATION_URL,
  SourceResponse.JSON_PROPERTY_KEY,
  SourceResponse.JSON_PROPERTY_SHARING_KEY
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-13T08:26:04.416037100-08:00[America/Los_Angeles]")
public class SourceResponse {
  public static final String JSON_PROPERTY_SOURCE_ID = "sourceId";
  private String sourceId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_CREATED = "created";
  private BigDecimal created;

  public static final String JSON_PROPERTY_IDENTITY = "identity";
  private String identity;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  private String destination;

  public static final String JSON_PROPERTY_ENCRYPTION_MODE = "encryptionMode";
  private String encryptionMode;

  public static final String JSON_PROPERTY_SECRET_REGION = "secretRegion";
  private String secretRegion;

  public static final String JSON_PROPERTY_LAST_USAGE = "lastUsage";
  private String lastUsage;

  public static final String JSON_PROPERTY_DAILY_USAGE = "dailyUsage";
  private List<SourceUsage> dailyUsage = null;

  public static final String JSON_PROPERTY_PERIOD_USAGE = "periodUsage";
  private List<SourceUsage> periodUsage = null;

  public static final String JSON_PROPERTY_APPLICATION_URL = "applicationUrl";
  private String applicationUrl;

  public static final String JSON_PROPERTY_KEY = "key";
  private String key;

  public static final String JSON_PROPERTY_SHARING_KEY = "sharingKey";
  private String sharingKey;

  public SourceResponse() { 
  }

  public SourceResponse sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Unique identifier of source.
   * @return sourceId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Unique identifier of source.")
  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSourceId() {
    return sourceId;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }


  public SourceResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Descriptive name of source.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Descriptive name of source.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public SourceResponse created(BigDecimal created) {
    this.created = created;
    return this;
  }

   /**
   * Timestamp of when source was created.
   * @return created
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Timestamp of when source was created.")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(BigDecimal created) {
    this.created = created;
  }


  public SourceResponse identity(String identity) {
    this.identity = identity;
    return this;
  }

   /**
   * Unique identity of source.
   * @return identity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Unique identity of source.")
  @JsonProperty(JSON_PROPERTY_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdentity() {
    return identity;
  }


  @JsonProperty(JSON_PROPERTY_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentity(String identity) {
    this.identity = identity;
  }


  public SourceResponse destination(String destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Destination of manifest for source (Encrypted and base64 encoded).
   * @return destination
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Destination of manifest for source (Encrypted and base64 encoded).")
  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDestination() {
    return destination;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestination(String destination) {
    this.destination = destination;
  }


  public SourceResponse encryptionMode(String encryptionMode) {
    this.encryptionMode = encryptionMode;
    return this;
  }

   /**
   * Mode of encryption used for destination data.
   * @return encryptionMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Mode of encryption used for destination data.")
  @JsonProperty(JSON_PROPERTY_ENCRYPTION_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncryptionMode() {
    return encryptionMode;
  }


  @JsonProperty(JSON_PROPERTY_ENCRYPTION_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncryptionMode(String encryptionMode) {
    this.encryptionMode = encryptionMode;
  }


  public SourceResponse secretRegion(String secretRegion) {
    this.secretRegion = secretRegion;
    return this;
  }

   /**
   * Region secret should be stored in.
   * @return secretRegion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Region secret should be stored in.")
  @JsonProperty(JSON_PROPERTY_SECRET_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecretRegion() {
    return secretRegion;
  }


  @JsonProperty(JSON_PROPERTY_SECRET_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecretRegion(String secretRegion) {
    this.secretRegion = secretRegion;
  }


  public SourceResponse lastUsage(String lastUsage) {
    this.lastUsage = lastUsage;
    return this;
  }

   /**
   * Last time anything was changed on this source
   * @return lastUsage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Last time anything was changed on this source")
  @JsonProperty(JSON_PROPERTY_LAST_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastUsage() {
    return lastUsage;
  }


  @JsonProperty(JSON_PROPERTY_LAST_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUsage(String lastUsage) {
    this.lastUsage = lastUsage;
  }


  public SourceResponse dailyUsage(List<SourceUsage> dailyUsage) {
    this.dailyUsage = dailyUsage;
    return this;
  }

  public SourceResponse addDailyUsageItem(SourceUsage dailyUsageItem) {
    if (this.dailyUsage == null) {
      this.dailyUsage = new ArrayList<>();
    }
    this.dailyUsage.add(dailyUsageItem);
    return this;
  }

   /**
   * Usage per day for the last month.
   * @return dailyUsage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Usage per day for the last month.")
  @JsonProperty(JSON_PROPERTY_DAILY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SourceUsage> getDailyUsage() {
    return dailyUsage;
  }


  @JsonProperty(JSON_PROPERTY_DAILY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDailyUsage(List<SourceUsage> dailyUsage) {
    this.dailyUsage = dailyUsage;
  }


  public SourceResponse periodUsage(List<SourceUsage> periodUsage) {
    this.periodUsage = periodUsage;
    return this;
  }

  public SourceResponse addPeriodUsageItem(SourceUsage periodUsageItem) {
    if (this.periodUsage == null) {
      this.periodUsage = new ArrayList<>();
    }
    this.periodUsage.add(periodUsageItem);
    return this;
  }

   /**
   * Usage per billing period over the last 2 years.
   * @return periodUsage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Usage per billing period over the last 2 years.")
  @JsonProperty(JSON_PROPERTY_PERIOD_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SourceUsage> getPeriodUsage() {
    return periodUsage;
  }


  @JsonProperty(JSON_PROPERTY_PERIOD_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriodUsage(List<SourceUsage> periodUsage) {
    this.periodUsage = periodUsage;
  }


  public SourceResponse applicationUrl(String applicationUrl) {
    this.applicationUrl = applicationUrl;
    return this;
  }

   /**
   * URL to application for source.
   * @return applicationUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL to application for source.")
  @JsonProperty(JSON_PROPERTY_APPLICATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApplicationUrl() {
    return applicationUrl;
  }


  @JsonProperty(JSON_PROPERTY_APPLICATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApplicationUrl(String applicationUrl) {
    this.applicationUrl = applicationUrl;
  }


  public SourceResponse key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Public key data for source
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Public key data for source")
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(String key) {
    this.key = key;
  }


  public SourceResponse sharingKey(String sharingKey) {
    this.sharingKey = sharingKey;
    return this;
  }

   /**
   * Base32 encoding of public key to use for encrypting share information
   * @return sharingKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Base32 encoding of public key to use for encrypting share information")
  @JsonProperty(JSON_PROPERTY_SHARING_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSharingKey() {
    return sharingKey;
  }


  @JsonProperty(JSON_PROPERTY_SHARING_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSharingKey(String sharingKey) {
    this.sharingKey = sharingKey;
  }


  /**
   * Return true if this SourceResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceResponse sourceResponse = (SourceResponse) o;
    return Objects.equals(this.sourceId, sourceResponse.sourceId) &&
        Objects.equals(this.name, sourceResponse.name) &&
        Objects.equals(this.created, sourceResponse.created) &&
        Objects.equals(this.identity, sourceResponse.identity) &&
        Objects.equals(this.destination, sourceResponse.destination) &&
        Objects.equals(this.encryptionMode, sourceResponse.encryptionMode) &&
        Objects.equals(this.secretRegion, sourceResponse.secretRegion) &&
        Objects.equals(this.lastUsage, sourceResponse.lastUsage) &&
        Objects.equals(this.dailyUsage, sourceResponse.dailyUsage) &&
        Objects.equals(this.periodUsage, sourceResponse.periodUsage) &&
        Objects.equals(this.applicationUrl, sourceResponse.applicationUrl) &&
        Objects.equals(this.key, sourceResponse.key) &&
        Objects.equals(this.sharingKey, sourceResponse.sharingKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceId, name, created, identity, destination, encryptionMode, secretRegion, lastUsage, dailyUsage, periodUsage, applicationUrl, key, sharingKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceResponse {\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    encryptionMode: ").append(toIndentedString(encryptionMode)).append("\n");
    sb.append("    secretRegion: ").append(toIndentedString(secretRegion)).append("\n");
    sb.append("    lastUsage: ").append(toIndentedString(lastUsage)).append("\n");
    sb.append("    dailyUsage: ").append(toIndentedString(dailyUsage)).append("\n");
    sb.append("    periodUsage: ").append(toIndentedString(periodUsage)).append("\n");
    sb.append("    applicationUrl: ").append(toIndentedString(applicationUrl)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    sharingKey: ").append(toIndentedString(sharingKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

